spring.application.name=cms
server.port=${PORT:8080}
# ENV CONFIG
spring.config.import=optional:file:.env.properties
# ========== DATASOURCE ==========
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA CONFIG
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# server.forward-headers-strategy=framework
